TOPDIR			:= ../../
IMAGE_NAME		:= vdesk-endless-sky-buster
AUTOGEN_SCRIPT		:= endless-sky
CONTAINER_NAME		:= vdesk-endless-sky-buster
CONTAINER_X11		:= yes
CONTAINER_DRI		:= yes

include $(TOPDIR)/common/std.mk
