TOPDIR			:= ../../
IMAGE_NAME		:= vdesk-thunderbird-buster
AUTOGEN_SCRIPT		:= vdesk-thunderbird
CONTAINER_NAME		:= vdesk-thunderbird-buster
CONTAINER_X11		:= yes
CONTAINER_DRI		:= yes

include $(TOPDIR)/common/std.mk
