TOPDIR			:= ../../
IMAGE_NAME		:= vdesk-libreoffice-buster
AUTOGEN_SCRIPT		:= vdesk-libreoffice
CONTAINER_NAME		:= vdesk-libreoffice-buster
CONTAINER_X11		:= yes
CONTAINER_DRI		:= yes

include $(TOPDIR)/common/std.mk
