TOPDIR			:= ../../
IMAGE_NAME		:= vdesk-chromium-ascii
AUTOGEN_SCRIPT		:= vdesk-chromium
CONTAINER_X11		:= yes
CONTAINER_DRI		:= yes
CONTAINER_NAME		:= vdesk-chromium-ascii

include $(TOPDIR)/common/std.mk
