TOPDIR			:= ../../
IMAGE_NAME		:= vdesk-freeorion-buster
AUTOGEN_SCRIPT		:= freeorion
CONTAINER_NAME		:= vdesk-freeorion-buster
CONTAINER_X11		:= yes
CONTAINER_DRI		:= yes
CONTAINER_AUDIO		:= yes

include $(TOPDIR)/common/std.mk
