#!/bin/bash

GIT_DIR="libdap.git"
SRC_VERSION="3.20.4"
RPM_NAME="libdap"
RPM_VERSION="${SRC_VERSION}-1"
PKG_DIR="$HOME/rpmbuild"
TARBALL_NAME="${PKG_DIR}/SOURCES/${RPM_NAME}-${SRC_VERSION}.tar.gz"
TARGET_DIR="sles12.5-pgbuild/files/src"

set -e

rm -Rf "${PKG_DIR}"
mkdir -p "${PKG_DIR}/SOURCES" "${PKG_DIR}/SPECS"

( cd $GIT_DIR && git archive --format tar HEAD ) | gzip > "${TARBALL_NAME}"
cp "$GIT_DIR/${RPM_NAME}.spec" "${PKG_DIR}/SPECS"

( cd $GIT_DIR && rpmbuild -bs "${RPM_NAME}.spec" )

mkdir -p ${TARGET_DIR}
cp "${PKG_DIR}/SRPMS/${RPM_NAME}-$RPM_VERSION.src.rpm" ${TARGET_DIR}
